name: swift_ride
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  animated_text_kit: ^4.2.3
  loading_animation_widget: ^1.3.0
  google_sign_in: ^7.1.0
  otp_text_field: ^1.1.3
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  image_picker: ^1.1.2
  google_place: ^0.4.7
  flutter_polyline_points: ^1.0.0
  geocoding: ^4.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_stripe: ^11.5.0
  http: ^0.13.6
  intl: ^0.20.2
  timezone: ^0.9.4
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter_native_splash:
  color: "#FD5858"
  image: assets/ic_launcher.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/google_logo.png
    - assets/apple.png
    - assets/van_logo.png
    - assets/onboarding_1.png
    - assets/onboarding_4.png
    - assets/onboarding_3.png
    - assets/map.png
    - assets/welcome.png
    - assets/pick.png
    - assets/drop.png
    - assets/map_style_light.json
    - assets/map_style_dark.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter_24pt-Bold.ttf
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 700

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
